services:
  opsbot:
    build: .
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"